### ISSUE TITLE
Add SQLite integration to fallbot

### ISSUE THREAD

**Issue by tomasohCHOM** [tomasohCHOM/fallbot#1]
## Idea

Create a SQLite table that stores basic owner information, along with an emergency contact number that the fallbot can use in case the owner needs major assistance. For instance, if fallbot has detected that the person has fallen (and for a considerably long time), the next step would be to get the emergency number from the db and send a text message (or alternatively an email).

## Procedure

We will use python's `sqlite` module which will make it easy to integrate the database with our scripts:

- Create a `db.py` which contains the main logic of how to interact with the db
- Make a `create_table` function that will create the `owner` table with the following attributes: username, password, email, first_name, last_name, emergency_contact (some of these fields may not be used but that is ok)
- `get_owner_info` will get the owner's username, email, first_name, and last_name and print them
- Create a `get_emergency_contact` function that will retrieve the emergency contact number from the db

## Resources

- [sqlite3 docs](https://docs.python.org/3/library/sqlite3.html)
- [example using sqlite3](https://github.com/tomasohCHOM/CanvasFindPeople/blob/main/main.py)

**Comment by MariiaGrushina** [comment]
Does it mean that there is only one owner in DB? Then for  `get_owner_info` and `get_emergency_contact` functions I just return "all" values form db? If not and there are multiple owners, then for the function `get_owner_info`, how I am suppose to identify which owner?
